"""bash completion emitter — neutral spec → a COMPREPLY-based completer that
counts positionals manually and dispatches on (command, index)/(command, flag)."""

from cc.completion import spec as _spec

_PROJECT_SQL = 'SELECT name FROM "project" ORDER BY name'
_ENV_SQL = 'SELECT name FROM "environment" ORDER BY name'


def _sql_reply(sql: str) -> str:
    return f"""COMPREPLY=( $(compgen -W "$(sqlite3 "$_cc_db" '{sql}' 2>/dev/null)" -- "$cur") )"""


def _snippet(source, cmd_names: str) -> str:
    """bash that sets COMPREPLY for a source (no trailing return)."""
    if not source:
        return ":"
    t = source["type"]
    if t == "entity":
        where = source.get("where", "")
        clause = (" " + where) if where else ""
        return _sql_reply(f'SELECT name FROM "{source["table"]}"{clause} ORDER BY name')
    if t == "values":
        return f'COMPREPLY=( $(compgen -W "{" ".join(source["values"])}" -- "$cur") )'
    if t == "module":
        return 'COMPREPLY=( $(compgen -W "$(__cc_modules)" -- "$cur") )'
    if t == "path":
        return 'COMPREPLY=( $(compgen -f -- "$cur") )'
    if t == "command":
        return f'COMPREPLY=( $(compgen -W "{cmd_names}" -- "$cur") )'
    if t == "env_target":
        # action is the first positional → at the dynamic argstart offset
        return (f'if [ "${{COMP_WORDS[argstart]}}" = list ]; then {_sql_reply(_PROJECT_SQL)}; '
                f'else {_sql_reply(_ENV_SQL)}; fi')
    return ":"


def render(commands, db) -> str:
    cmd_names = " ".join(c["name"] for c in commands)
    grp = _spec.groups(commands)

    flag_cases, flagvalue_cases, valueflag_pred, positional_cases = [], [], [], []
    # leaf key: ":"-joined path ("switch", "db:use") — matches the $cmd built at runtime
    for path, c in _spec.iter_leaves(commands):
        key = ":".join(path)
        all_flags = [fn for o in c["options"] for fn in o["names"]]
        if all_flags:
            flag_cases.append(f'    {key}) COMPREPLY=( $(compgen -W "{" ".join(all_flags)}" -- "$cur") ) ;;')
        for o in c["options"]:
            if not o["takes_value"]:
                continue
            snip = _snippet(o["source"], cmd_names)
            for fn in o["names"]:
                flagvalue_cases.append(f'    {key}:{fn}) {snip}; return ;;')
                valueflag_pred.append(f'    {key}:{fn}) return 0 ;;')
        for idx, p in enumerate(c["positionals"], start=1):
            snip = _snippet(p["source"], cmd_names)
            pkey = f"{key}:*" if p["multi"] else f"{key}:{idx}"
            positional_cases.append(f'    {pkey}) {snip} ;;')

    group_verb_cases = "\n".join(
        f'    {g}) echo "{" ".join(verbs)}" ;;' for g, verbs in grp.items()
    )

    return (
        _TEMPLATE
        .replace("%DB%", db)
        .replace("%CMD_NAMES%", cmd_names)
        .replace("%GROUPS%", " ".join(grp.keys()))
        .replace("%GROUP_VERBS%", group_verb_cases)
        .replace("%VALUEFLAG_PRED%", "\n".join(valueflag_pred))
        .replace("%FLAGVALUE_CASES%", "\n".join(flagvalue_cases))
        .replace("%FLAG_CASES%", "\n".join(flag_cases))
        .replace("%POSITIONAL_CASES%", "\n".join(positional_cases))
    )


_TEMPLATE = r"""# cc bash completion — generated by `cc completion bash`
# Source it:  source ~/.cc-cli/shell/cc.completion.bash

_cc_db="%DB%"

__cc_modules() {
  local p d
  p=$(sqlite3 "$_cc_db" 'SELECT e.project_path FROM app_state a JOIN environment e ON e.id = a.environment_id ORDER BY a.id DESC LIMIT 1' 2>/dev/null)
  [ -n "$p" ] && [ -d "$p" ] || return
  for d in "$p"/*/; do [ -d "$d" ] && basename "$d"; done
}

__cc_is_valueflag() {  # $1=cmd $2=flag → 0 if that flag takes a value
  case "$1:$2" in
%VALUEFLAG_PRED%
    *) return 1 ;;
  esac
}

__cc_is_group() {  # $1=name → 0 if it's a noun-group (cc <group> <verb>)
  local g
  for g in %GROUPS%; do [ "$g" = "$1" ] && return 0; done
  return 1
}

__cc_group_verbs() {  # $1=group → echo its verbs
  case "$1" in
%GROUP_VERBS%
  esac
}

_cc() {
  local cur prev g cmd argstart pos i w
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  COMPREPLY=()

  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "%CMD_NAMES%" -- "$cur") )
    return
  fi

  # resolve the command key: a noun-group folds its verb into "group:verb"
  g="${COMP_WORDS[1]}"
  if __cc_is_group "$g"; then
    if [ "$COMP_CWORD" -eq 2 ]; then
      COMPREPLY=( $(compgen -W "$(__cc_group_verbs "$g")" -- "$cur") )
      return
    fi
    cmd="$g:${COMP_WORDS[2]}"
    argstart=3
  else
    cmd="$g"
    argstart=2
  fi

  # value for a flag just typed
  case "$cmd:$prev" in
%FLAGVALUE_CASES%
  esac

  # completing a flag itself
  if [[ "$cur" == -* ]]; then
    case "$cmd" in
%FLAG_CASES%
    esac
    return
  fi

  # which positional are we on? skip flags and their values
  pos=0; i=$argstart
  while [ "$i" -lt "$COMP_CWORD" ]; do
    w="${COMP_WORDS[i]}"
    if [[ "$w" == -* ]]; then
      if __cc_is_valueflag "$cmd" "$w"; then i=$((i+2)); else i=$((i+1)); fi
      continue
    fi
    pos=$((pos+1)); i=$((i+1))
  done
  pos=$((pos+1))

  case "$cmd:$pos" in
%POSITIONAL_CASES%
  esac
}

complete -F _cc cc
"""
