"""fish completion emitter — neutral spec → declarative `complete -c cc` rules,
gating positionals with `__fish_seen_subcommand_from` (no position indices)."""
import re

from cc.completion import spec as _spec

_ENV_TARGET_ENV_VERBS = "delete edit archive activate merged pin unpin"


def _clean(text: str) -> str:
    return (text or "").replace("'", "").strip()


def _helper(table: str) -> str:
    return "__cc_ent_" + re.sub(r"[^a-zA-Z0-9]", "_", table)


def _src_args(source) -> str:
    """The `-a '...'` / `-F` suffix for a source (empty = no candidates)."""
    if not source:
        return ""
    t = source["type"]
    if t == "entity":
        return f"-a '({_helper(source['table'])})'"
    if t == "values":
        return f"-a '{' '.join(_clean(v) for v in source['values'])}'"
    if t == "module":
        return "-a '(__cc_modules)'"
    if t == "command":
        return "-a '(__cc_commands)'"
    if t == "path":
        return "-F"
    return ""


def _emit_body(out, cmd, seen_cond):
    """Emit the options + positionals of `cmd`, every rule gated on `seen_cond`
    (the condition that `cmd` is the active command — top-level or group verb)."""
    for o in cmd["options"]:
        parts = [f"complete -c cc -n '{seen_cond}'"]
        for nm in o["names"]:
            if nm.startswith("--"):
                parts.append(f"-l {nm[2:]}")
            elif nm.startswith("-"):
                parts.append(f"-s {nm[1:]}")
        if o["takes_value"]:
            parts.append("-r")
            args = _src_args(o["source"])
            if args:
                parts.append(args)
        if o["help"]:
            parts.append(f"-d '{_clean(o['help'])}'")
        out.append(" ".join(parts))

    # first positional may be a verb set — gate later positionals to "verb chosen"
    verbs = None
    if cmd["positionals"]:
        first = cmd["positionals"][0]["source"]
        if first and first.get("type") == "values":
            verbs = first["values"]

    for idx, p in enumerate(cmd["positionals"]):
        src = p["source"]
        if src and src.get("type") == "env_target":
            out.append(f"complete -c cc -n '{seen_cond}; and __fish_seen_subcommand_from list' -a '({_helper('project')})'")
            out.append(f"complete -c cc -n '{seen_cond}; and __fish_seen_subcommand_from {_ENV_TARGET_ENV_VERBS}' -a '({_helper('environment')})'")
            continue
        args = _src_args(src)
        if not args:
            continue
        if idx == 0 and verbs:
            cond = f"{seen_cond}; and not __fish_seen_subcommand_from {' '.join(verbs)}"
        elif idx == 0:
            cond = seen_cond
        else:
            cond = seen_cond
            if verbs:
                cond += f"; and __fish_seen_subcommand_from {' '.join(verbs)}"
        out.append(f"complete -c cc -n '{cond}' {args}")


def render(commands, db) -> str:
    out = [
        "# cc fish completion — generated by `cc completion fish`",
        "# Source it:  source ~/.cc-cli/shell/cc.completion.fish",
        "",
        f"set -g _cc_db '{db}'",
        "",
    ]

    for table, where in _spec.entity_tables(commands).items():
        clause = (" " + where) if where else ""
        sql = f'SELECT name FROM "{table}"{clause} ORDER BY name'
        out.append(f"function {_helper(table)}; sqlite3 $_cc_db '{sql}' 2>/dev/null; end")
    out.append(
        "function __cc_modules; set -l p (sqlite3 $_cc_db "
        "'SELECT e.project_path FROM app_state a JOIN environment e ON e.id = a.environment_id ORDER BY a.id DESC LIMIT 1' 2>/dev/null); "
        "test -n \"$p\"; and test -d \"$p\"; and for d in $p/*/; basename $d; end; end"
    )
    out.append("function __cc_commands; printf '%s\\n' " + " ".join(c["name"] for c in commands) + "; end")
    out.append("")
    # no bare file completion unless a rule asks (-F)
    out.append("complete -c cc -f")
    out.append("")

    for c in commands:
        name = c["name"]
        subs = c.get("subcommands") or []
        out.append(f"complete -c cc -n __fish_use_subcommand -a {name} -d '{_clean(c['help'])}'")

        if not subs:
            _emit_body(out, c, f"__fish_seen_subcommand_from {name}")
            continue

        # noun-group: its own (root) flags, then the verbs, then each verb's args
        _emit_body(out, {"name": name, "options": c["options"], "positionals": []},
                   f"__fish_seen_subcommand_from {name}")
        allverbs = " ".join(s["name"] for s in subs)
        for s in subs:
            out.append(
                f"complete -c cc -n '__fish_seen_subcommand_from {name}; "
                f"and not __fish_seen_subcommand_from {allverbs}' -a {s['name']} -d '{_clean(s['help'])}'"
            )
        for s in subs:
            seen = f"__fish_seen_subcommand_from {name}; and __fish_seen_subcommand_from {s['name']}"
            _emit_body(out, s, seen)

    return "\n".join(out) + "\n"
