"""zsh completion emitter — neutral spec → an _arguments-based completer."""
import re

from cc.completion import spec as _spec

_FORBIDDEN = "[]:'`\"()"


def _clean(text: str) -> str:
    out = (text or "").strip()
    for ch in _FORBIDDEN:
        out = out.replace(ch, "")
    return out


def _helper(table: str) -> str:
    return "_cc_ent_" + re.sub(r"[^a-zA-Z0-9]", "_", table)


def _action(source) -> str:
    """The zsh completion action for a source (used after `:name:`)."""
    if not source:
        return ""
    t = source["type"]
    if t == "entity":
        return _helper(source["table"])
    if t == "values":
        return "(" + " ".join(_clean(v) for v in source["values"]) + ")"
    if t == "module":
        return "_cc_modules"
    if t == "path":
        return "_files"
    if t == "env_target":
        return "_cc_env_target"
    if t == "command":
        return "_cc_cmdnames"
    return ""


def _option_spec(opt) -> str:
    names = opt["names"]
    help_text = _clean(opt["help"])
    tail = f":arg:{_action(opt['source'])}" if opt["takes_value"] else ""
    if len(names) >= 2:
        excl = "(" + " ".join(names) + ")"
        brace = "{" + ",".join(names) + "}"
        return f"'{excl}'{brace}'[{help_text}]{tail}'"
    return f"'{names[0]}[{help_text}]{tail}'"


def _positional_spec(pos, idx) -> str:
    slot = "*" if pos["multi"] else str(idx)
    return f"'{slot}:{pos['name']}:{_action(pos['source'])}'"


def _group_helper(name: str) -> str:
    return "_cc_" + re.sub(r"[^a-zA-Z0-9]", "_", name) + "_cmds"


def _arg_specs(cmd) -> list[str]:
    specs = [_option_spec(o) for o in cmd["options"]]
    for idx, p in enumerate(cmd["positionals"], start=1):
        specs.append(_positional_spec(p, idx))
    return specs


def _dispatch_case(cmd, group_helpers: dict) -> str:
    """One `case` branch. A leaf dispatches its args; a group peels a level
    (`_arguments -C` re-shifts $words so $words[1] becomes the verb) and recurses."""
    name = cmd["name"]
    subs = cmd.get("subcommands") or []
    if not subs:
        specs = _arg_specs(cmd)
        if specs:
            body = " \\\n          ".join(specs)
            return f"    {name})\n      _arguments \\\n          {body} ;;"
        return f"    {name}) ;;"

    helper = _group_helper(name)
    group_helpers[helper] = " ".join(s["name"] for s in subs)
    pre = "".join(_option_spec(o) + " " for o in cmd["options"])  # group-root flags
    inner = "\n".join(_dispatch_case(s, group_helpers) for s in subs)
    return (
        f"    {name})\n"
        f"      _arguments -C {pre}'1: :{helper}' '*::arg:->args'\n"
        f"      [[ $state == args ]] || return\n"
        f"      case $words[1] in\n"
        f"{inner}\n"
        f"      esac ;;"
    )


def render(commands, db) -> str:
    describe = "\n".join(f"    '{c['name']}:{_clean(c['help'])}'" for c in commands)
    cmd_names = " ".join(c["name"] for c in commands)

    ent_lines = []
    for table, where in _spec.entity_tables(commands).items():
        clause = (" " + where) if where else ""
        sql = f'SELECT name FROM "{table}"{clause} ORDER BY name'
        ent_lines.append(f"{_helper(table)}() {{ _cc_sql '{sql}' }}")
    ent_helpers = "\n".join(ent_lines)

    group_helpers: dict = {}
    dispatch = "\n".join(_dispatch_case(c, group_helpers) for c in commands)
    grp_lines = "\n".join(f"{fn}() {{ compadd {verbs} }}" for fn, verbs in group_helpers.items())

    return (
        _TEMPLATE
        .replace("%DB%", db)
        .replace("%DESCRIBE%", describe)
        .replace("%CMD_NAMES%", cmd_names)
        .replace("%ENT_HELPERS%", ent_helpers)
        .replace("%GROUP_HELPERS%", grp_lines)
        .replace("%DISPATCH%", dispatch)
    )


_TEMPLATE = r"""# cc zsh completion — generated by `cc completion zsh`
# Source after compinit:  source ~/.cc-cli/shell/cc.completion.zsh

typeset -g _cc_db="%DB%"

_cc_sql() {  # $1 = SQL; add each row as a candidate
  [[ -f "$_cc_db" ]] || return
  local -a rows
  rows=(${(f)"$(sqlite3 "$_cc_db" "$1" 2>/dev/null)"})
  (( ${#rows} )) && compadd -a rows
}
%ENT_HELPERS%
_cc_modules() {
  local p
  p=$(sqlite3 "$_cc_db" 'SELECT e.project_path FROM app_state a JOIN environment e ON e.id = a.environment_id ORDER BY a.id DESC LIMIT 1' 2>/dev/null)
  [[ -n "$p" && -d "$p" ]] || return
  local -a rows; rows=(${p}/*(/N:t)); (( ${#rows} )) && compadd -a rows
}
_cc_env_target() {  # cc project env <action> <target>: project for `list`, env otherwise
  case ${words[2]} in
    list) _cc_ent_project ;;
    delete|edit|archive|activate|merged|pin|unpin) _cc_ent_environment ;;
  esac
}
_cc_cmdnames() { compadd %CMD_NAMES% }
%GROUP_HELPERS%
_cc_commands() {
  local -a cmds
  cmds=(
%DESCRIBE%
  )
  _describe -t commands 'cc command' cmds
}

_cc() {
  local curcontext="$curcontext" state line
  typeset -A opt_args
  _arguments -C \
    '(-d --debug)'{-d,--debug}'[Verbose debug logging]' \
    '(-v --version)'{-v,--version}'[Show version]' \
    '1: :_cc_commands' \
    '*::arg:->args'
  [[ $state == args ]] || return
  case $words[1] in
%DISPATCH%
  esac
}

# Ensure the completion system is loaded (it normally is under oh-my-zsh etc.).
(( $+functions[compdef] )) || { autoload -Uz compinit && compinit -u }
compdef _cc cc
"""
