preview = true
line-length = 120
lint.select = ["C", "E", "F", "W", "B", "B9", "I"]
lint.ignore = ["E501", "C901"]
lint.per-file-ignores = { "__init__.py" = ["F401", "I001"], "setup.py" = ["F401", "I001"] }
