"""`cc completion <shell>` — emit a native completion script for zsh/bash/fish,
generated by introspecting argparse so it can't drift from the real CLI."""
from cc.base.command import Command
from cc.completion import bash as _bash
from cc.completion import fish as _fish
from cc.completion import spec as _spec
from cc.completion import zsh as _zsh

_EMITTERS = {"zsh": _zsh.render, "bash": _bash.render, "fish": _fish.render}


class CompletionCommand(Command):
    group = "config"
    name = "completion"
    description = "Print a shell completion script (zsh, bash, fish)"

    def arguments(self):
        return [
            self.Argument(
                names=["shell"],
                nargs="?",
                choices=["zsh", "bash", "fish"],
                default=None,
                help="Shell to emit a completion script for. Omit to auto-detect.",
            ),
        ]

    def execute(self):
        shell = getattr(self.args, "shell", None) or self._detect_shell()
        if shell not in _EMITTERS:
            from cc.utils.console import get_error_console
            get_error_console().print(
                f"[error]Can't emit completion for '{shell or 'unknown shell'}'.[/] "
                "Supported: zsh, bash, fish."
            )
            return False
        commands = _spec.build(self.parser)
        print(_EMITTERS[shell](commands, self.Constants.SQLITE_DB_PATH))
        return True

    @staticmethod
    def _detect_shell():
        try:
            from cc.shell.installer import detect_shell
            return detect_shell()
        except Exception:
            return None
